# Generated by Django 2.2.7 on 2019-11-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=50, verbose_name='Планета')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
                'ordering': ['planet_name'],
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Зарегистрирован')),
                ('answer_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ на вопрос №1')),
                ('answer_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ на вопрос №2')),
                ('answer_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ на вопрос №3')),
                ('planet_habitat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rservice.Planet', verbose_name='Планета обитания')),
            ],
            options={
                'verbose_name': 'Рекрут',
                'verbose_name_plural': 'Рекруты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sith_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('learning_planet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rservice.Planet', verbose_name='Планета обучения')),
                ('shadow_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rservice.Recruit', verbose_name='Рука Тени')),
            ],
            options={
                'verbose_name': 'Ситх',
                'verbose_name_plural': 'Ситхи',
                'ordering': ['sith_name'],
            },
        ),
    ]
